### ISSUE TITLE
ParaSurf: xyz/uv values for normal vector

### ISSUE THREAD

**Issue by Evan-CTL** [ccnmtl/3demos#348]
Parametric surface needs some work in order to render the tangent plane and normal vector. Specifically some sort of conversion between the uv values and the xyz values. [Threejs raycaster objects do have uv properties](https://threejs.org/docs/#api/en/core/Raycaster) so this might not be too bad.

**Comment by drewyoungren** [comment]
I pushed a branch [make-parsurf-tans-work](https://github.com/ccnmtl/mathplayground/tree/make-parsurf-tans-work) that addresses this. 

Good news: tangent vectors are there. Usual key bindings:
  - `t`: Toggle the tangent frame
  - `n`: Toggle the normal vector
  - `y`: Toggle piece of tangent plane

Less good news: I really struggled with updating the parameters properly. Some play between the reactivity, the input components, and the `onUpdate` callback were overwriting parameters in an inexplicable (and not always repeatable!) way. Watch the $x(u,v)$ field: 

![weird replacement](https://user-images.githubusercontent.com/19934878/222330712-6bf23e2a-bea7-423f-baf2-1b67fcc0d37b.gif)

Not worth trying to duplicate this as it was likely a bug I introduced and squashed, but I may have ripped out some functionality from ParSurf in the process. Will make an issue tomorrow or Friday on it.
