### ISSUE TITLE
Object data merging on delete

### ISSUE THREAD

**Issue by Evan-CTL** [ccnmtl/3demos#385]
I've noticed odd bugs in the `Vector` and `Space Curve`. This happens in production as well, both in and out of a room.

1. The object itself is deleted, but the parameters of every object in the list above the deleted object are shifted up one to the above list entry, but the original colors of that list remain the same.
2. Even though the parameters have been modified the object does not change. Even when you modify a parameter only that one parameter is affected.
3. The delete animation looks like the delete is happening at the top of the list. This might hint at the behavior of the bug. Maybe the first list element is deleted along with their parameter data, and so the rest of the list is preserved? But the colors are unaffected for some reason. In which case the object is properly deleted and it is just the list items that are screwy.

This requires some investigating. Here a third vector was deleted and now these two vectors don't correspond to their objects, but notably the red vector params match the state of the blue vector
![Screenshot 2023-03-01 at 4 45 14 PM](https://user-images.githubusercontent.com/107073665/222271899-99879305-3d34-49e1-b7df-5bb58d796d4b.png)

**Comment by Evan-CTL** [comment]
This is true for Space Curves and Graph of Function objects too. Potentially all objects, but I have to test them.

**Comment by drewyoungren** [comment]
Fixed by keying the each block.
