### ISSUE TITLE
Space Curves publish overwrite not working

### ISSUE THREAD

**Issue by Evan-CTL** [ccnmtl/3demos#386]
If you publish a Space Curve, then delete it, create a new one, modify it (make sure to change the color), and publish the published curve remains the same, except the color changes.

I'm wondering if this happens for the same reason that issue https://github.com/ccnmtl/mathplayground/issues/385 is happening?

**Comment by drewyoungren** [comment]
Can this be closed? I can't replicate it.

**Comment by Evan-CTL** [comment]
Yes, it looks like it was resolved with the keyed each function.
