### ISSUE TITLE
Implement object selection in scene

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/3demos#391]
See hover implementation here: 
* https://github.com/ccnmtl/astro-simulations/blob/master/sun-motion-simulator/src/CelestialSphere.jsx#L926
* https://discourse.threejs.org/t/finding-nearest-vertex-of-a-mesh-to-mouse-cursor/4167/1

**Comment by Evan-CTL** [comment]
Possible approaches:
- Lower opacity on all unselected objects, probably the easiest approach
- The highlight option isn't a bad idea, there is [an example in the THREE.js documentation](https://threejs.org/examples/?q=outline#webgl_postprocessing_outline)
- If we make it brighter we'd have to put restrictions on the color picker options
  - Alternatively, make all the other objects darker. This might help the selected object to pop more without washing out the details of the grid overlay or curve features.

**Comment by nikolas** [comment]
Cool - yeah, I like the idea of doing the outline in post-processing, like that three.js example.
