### ISSUE TITLE
Weird low-res three.js display when joining a room that happens to be animating

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/3demos#405]
Tested on animating space curve. I've seen this bug a while ago too, so it wasn't a recent change that caused this. Worth looking into.

![Screenshot_2023-03-07_16-48-38](https://user-images.githubusercontent.com/59292/223561011-3d0fb0ff-8788-40c9-b0f4-5a568c1040bd.png)

To reproduce:
* As the host of a room, make a space curve, animate it, and publish.
* Join the room in private tab as student.

The display is fixed on the student side if the host removes the objects and publishes again.

**Comment by Evan-CTL** [comment]
It might be a feature to prevent slowdown on animation.
