### ISSUE TITLE
403 error on URL hash (production)

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/3demos#413]
We need to adjust some firewall rules: Drew mentioned this but i'm having trouble reproducing.

e.g., this appears to be okay: https://3demos.ctl.columbia.edu/?currentChapter=Intro&flipInfo=true&obj0_kind=level&obj0_color=%233232ff&obj0_params_g=x%5E2+%2B+2+y%5E2+-+z%5E2&obj0_params_k=1&obj0_params_a=-2&obj0_params_b=2&obj0_params_c=-2&obj0_params_d=2&obj0_params_e=-2&obj0_params_f=2

**Comment by drewyoungren** [comment]
![403](https://user-images.githubusercontent.com/19934878/223878346-12d9b138-4276-4f63-a827-b95f444998e5.gif)

**Comment by nikolas** [comment]
Cool - I'm sure I can find this event in our logs and make the adjustment now, one sec.

**Comment by nikolas** [comment]
So I added an exception for the firewall rule being triggered here last night. I'm unable to reproduce the problem myself in my testing, but please let me know if you see this again and I'll add more exceptions where necessary.
