### ISSUE TITLE
Panel extends below the visible elements, obstructing the canvas

### ISSUE THREAD

**Issue by Evan-CTL** [ccnmtl/3demos#486]
Canvas does not respond to clicks or drags beneath the visible elements of the Panel. The panel div extends to the bottom of the page and overlaps the canvas, though it's not initially obvious

**Comment by nikolas** [comment]
I did some experimentation to resolve this, but the solution is still in progress.

We can easily set `height: fit-content` on the `.demos-panel`, which almost does what we want. But there's an issue with the objects dropdown extending past the content:
![Screenshot_2023-04-06_16-19-10](https://user-images.githubusercontent.com/59292/230485676-fced8fd9-4129-40ad-a1fd-100a0d068f11.png)

**Comment by Evan-CTL** [comment]
Didn't mean to close the issue, sorry about that. I found a lead on a possible solution.
`.demos-mainview { overflow: auto; } .demos-panel { height:fit-content; overflow: visible; }` 
This allows scrolling --though the scroll bar isn't visible-- and it does scroll with tabbing. The one drawback is that it breaks the little widget that allows horizontal panel resize. I propose that we switch the upper right panel button that hides the panel to double as a drag tab for resizing. Something like: 
- **Click and drag**: resizes the panel
- **Double-click**: Hides/Shows the panel

**Comment by nikolas** [comment]
After all my panel changes from yesterday, this bug is in fact still around. I'll have to take another look.

**Comment by drewyoungren** [comment]
I appreciate what a pesky little thing this can be. It seems there was a solution in bootstrap 4 that did not make it to 5.

[https://stackoverflow.com/questions/70098157/bootstrap-5-1-3-dropdown-data-bs-boundary-no-longer-works](https://stackoverflow.com/questions/70098157/bootstrap-5-1-3-dropdown-data-bs-boundary-no-longer-works)

I just know so little about styling in general. How is it that the `overflow-y` seems to "know" about the absolutely-positioned dropdown-menu, but the `height: fit-content` doesn't?
