### ISSUE TITLE
mathplayground.ctl.columbia.edu cannot access rooms

### ISSUE THREAD

**Issue by Evan-CTL** [ccnmtl/3demos#497]
The [mathplayground.ctl.columbia.edu](http://mathplayground.ctl.columbia.edu/) address is still working, but if you try to make a room then it throws a 403 about the CSRF verification.

Either add the address to our white list or remove the route entirely.

**Comment by nikolas** [comment]
I've set up forwarding rules in nginx, so mathplayground.ctl will now forward to 3demos.ctl.
