### ISSUE TITLE
Artifacts from outline

### ISSUE THREAD

**Issue by drewyoungren** [ccnmtl/3demos#526]
#522 has to be reverted. Look at the artifacts from intersections:

![artifacts-outilnes](https://user-images.githubusercontent.com/19934878/233667822-92bc0fd1-5c10-485a-a0df-3f3dcc34e79f.gif)

Here is one commit before (3d3a647):

![artifacts-3d3a647](https://user-images.githubusercontent.com/19934878/233667950-91ba23c3-c1a4-42f1-9e9a-6002df6c73e1.gif)

**Comment by nikolas** [comment]
Oh weird - appears to be specific to Chrome, I'm not seeing this on Firefox in my testing.

**Comment by nikolas** [comment]
I'm taking a look to see if I can resolve this without reverting.

**Comment by nikolas** [comment]
I disabled the problematic part of the new rendering flow for now (https://github.com/ccnmtl/3demos/commit/adbf5e5f4403fdac87dcc6bb501c987ac0050974)

It looks like Three.js's [OutlinePass](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/postprocessing/OutlinePass.js) is doing some downsampling. Related issues with this noted here: https://stackoverflow.com/q/21050797/173630

I wasn't able to resolve these issues yet after messing with the resolution and downsampling config a bunch. So, we'll see if we can get this working and be more aware of maintaining the existing clean render going forward.
