### ISSUE TITLE
Make `iframe`able

### ISSUE THREAD

**Issue by drewyoungren** [ccnmtl/3demos#759]
I'd like to try embedding iframes in a [reveal.js](https://revealjs.com/) slideshow. Can we change this option?
> Refused to display `https://3demos.ctl.columbia.edu/` in a frame because it set `X-Frame-Options` to `deny`.

**Comment by drewyoungren** [comment]
I just have them sitting in a [repo](https://github.com/drewyoungren/mvc-slides) and [served](https://drew.youngren.nyc/mvc-slides) via Github Pages. I suppose I could move them to the same repo and serve from there, but that seems like project bloat.

**Comment by Evan-CTL** [comment]
No that should be fine. you just have to set the Content-Security-Policy on that end and we can update the 3Demos header

**Comment by drewyoungren** [comment]
Closed by #782
